# Generated by Django 3.2.8 on 2021-11-22 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211122_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='names_tags',
            old_name='main',
            new_name='is_main',
        ),
        migrations.AlterField(
            model_name='names_tags',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='names_tags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tags',
            field=models.ManyToManyField(related_name='scopess', through='articles.Names_tags', to='articles.Article'),
        ),
    ]
